variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - module load python3 rh/devtoolset/7 cuda cudatoolkit

stages:
  - lint_python
  - regression_cpu
  - regression_gpu

lint_python-job:
  stage: lint_python
  tags:
    - ias-cuda01
  only:
    - master
    - merge_requests
  script:
    - cd $CI_PROJECT_DIR
    - python3 -m pip install --user flake8
    - echo "Running flake8..."
    - python3 -m flake8
      --exclude=kokkos >> $CI_PROJECT_DIR/tst/lint_python_log.txt
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - $CI_PROJECT_DIR/tst/lint_python_log.txt

regression_cpu-job:
  stage: regression_cpu
  tags:
    - ias-cuda01
  only:
    - master
    - merge_requests
  script:
    - cd $CI_PROJECT_DIR/tst
    - echo "Running regression script on CPU..."
    - python3 run_tests.py --log_file=log_file_cpu.txt
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - $CI_PROJECT_DIR/tst/log_file_cpu.txt

regression_gpu-job:
  stage: regression_gpu
  tags:
    - ias-cuda01
  only:
    - master
    - merge_requests
  script:
    - cd $CI_PROJECT_DIR/tst
    - echo "Running regression script on GPU..."
    - python run_tests.py --log_file=log_file_gpu.txt
      --cmake=-DKokkos_ENABLE_CUDA=On
      --cmake=-DKokkos_ARCH_VOLTA70=On
      --cmake=-DCMAKE_CXX_COMPILER=$CI_PROJECT_DIR/kokkos/bin/nvcc_wrapper
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - $CI_PROJECT_DIR/tst/log_file_gpu.txt
